-- Bronze/Silver/Gold schema and database setup for DE Challenge 2026
-- Co-authored with CoCo

USE ROLE ACCOUNTADMIN;

-- Database
CREATE DATABASE IF NOT EXISTS DE_CHALLENGE;

-- Schemas (Medallion)
CREATE SCHEMA IF NOT EXISTS DE_CHALLENGE.BRONZE;
CREATE SCHEMA IF NOT EXISTS DE_CHALLENGE.SILVER;
CREATE SCHEMA IF NOT EXISTS DE_CHALLENGE.GOLD;
